### PR TITLE
House Budget App - ROR Capstone Project

### PR DESCRIPTION
**Pull request by emhamza**
### This is the new milestone my journey at Microverse - where I have managed to develop a ROR app for House Budget. 🎉 

**[Presentation link here
](https://www.loom.com/share/92a35f3b198c4d50b352c85ab1baa4f2?sid=a090e7ef-00c5-4f4e-88d9-0977e0ebc1ba)** 

**Following are the tasks that I have accomplished in this project:**

### 1. Create a Ruby on Rails application that allows the user to:

- register and log in, so that the data is private to them.
- introduce new transactions associated with a category.
- see the money spent on each category.

### 2. Add the following pages:

- Splash screen
- Sign up and log in pages
- Home page (categories page)
- Transactions page
- "Add a new category" page
- Add a new transaction" page

### 3. Other Features:
- Add Unit Tests

### CODE REVIEW

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @emhamza, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Required Changes ♻️
- [x] [REQUIRED] Good job so far! It would be nice implement your design `layout` part to like a [Behance design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=) and please mention to mobile screen because on mobile size your project's most section elements display not as [Behance](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=)🙏🏼 

image

image

- [x] [REQUIRED] Good job so far! Please fix the failed `spec` becasue all tests should pass 🙏🏼 

image

_Check the comments under the review._

## Optional suggestions
- [x] [OPTIONAL] It would be nice if you implement correct submition to your branch because I can not see your other files 🙏🏼 

image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emhamza** [comment]
@mukhammadrizooff Thank you so much for your feedback, It is really progressive.
For unit test - Every test is already passing from my side: 👇 

Screenshot 2023-08-11 at 4 17 12 PM

For Add button - Since there is no functionality of the scan button therefore I added add button with plus to give it a professional look! Please consider this point while reviewing. Thank you 🔢 🍔

**Review by fobadara — CHANGES_REQUESTED** [review]
Hi @emhamza, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Proper implementation of reviewer's requirements
✅ Clean code

## Required Changes ♻️
_Check the comments under the review._

[REQUIRED] As stated by the previous reviewer the design for your homepage is different from that which is on BEHANCE. Kindly fix this.
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @emhamza 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.

## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Pull request merged**
